spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.5.255:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: test
      password: test123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update